import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

// 边缘运行时
// export const runtime = "edge";

// nodejs 运行时
export const runtime = "nodejs";
// dynamic 将布局或页面的动态行为更改为完全静态或完全动态
export const dynamic = "force-static"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
